### ISSUE TITLE
Using go-libutp in meshbird

### ISSUE THREAD

**Issue by rmnoff** [anacrolix/go-libutp#10]
Hello! I have successfully implemented go-libutp into meshbird (see my fork), but currently I am struggling with UTP_ETIMEOUT. For me it seems like there is too little time for request. While scanning my traffic via Wireshark, I've mentioned that req-resp time could go up to 20 mins. It is a lot of time, but at least something happens. How can I increase time so I may see if it will help me solve the problem I have.

**Comment by rmnoff** [comment]
No comments needed. It works now.

**Comment by anacrolix** [comment]
Did you find what you needed, or was the error something else? I cannot find your fork.
