### ISSUE TITLE
[BUG] Reading produce UTP_ECONNRESET on client side under an heavy load of the server.

### ISSUE THREAD

**Issue by Jorropo** [anacrolix/go-libutp#13]
While remaking a [transport the transport for libp2p lib](https://github.com/libp2p/go-utp-transport) I was getting some `stream error` under one test, this test was making a lot of connection, after some digging I found these error are coming when some layer tries to read from the Conn object.

Here is my bug reproducing repo :
[/ipfs/QmQvCivXZtrK87DgEBK2LJDwYCSiANdVHCsdxaV8n5abFn](https://jorropo.ovh/ipfs/QmQvCivXZtrK87DgEBK2LJDwYCSiANdVHCsdxaV8n5abFn)
To reproduce the bug just build it and start it.
It will create one utp socket on `127.0.0.1:4500` wich accept and start an handler function wich just read and write what it read until the conn die.
After it start 100 goroutine each creating a new socket and dialling the first socket, then sending an array of byte and verifying what was sended and what was received is the same.
Then most of the time (it never not happend to me but the number of times vary a lot, if for you it doesn't trigger maybe try with more dialler (via the test var, also the addr is not used in the dialler (I forgoted to put it also here) so if you must change it change it also in the hi func)).
And you should see some `UTP_ECONNRESET` errors.
As you can see that an sample case :
```
At connector 16 error for reading:
UTP_ECONNRESET
At connector 82 error for reading:
UTP_ECONNRESET
At connector 18 error for reading:
UTP_ECONNRESET
At connector 46 error for reading:
UTP_ECONNRESET
At connector 66 error for reading:
UTP_ECONNRESET
At connector 68 error for reading:
UTP_ECONNRESET
At connector 92 error for reading:
UTP_ECONNRESET
At connector 14 error for reading:
UTP_ECONNRESET
At connector 83 error for reading:
UTP_ECONNRESET
At connector 44 error for reading:
UTP_ECONNRESET
```

**Comment by anacrolix** [comment]
What OS? This is tricky territory, because you may just be stress-testing the underlying UDP implementation. Running with `while ./test; do sleep 3; done`, and increasing the sleep time decreases the number of these errors I get.

There's also a mistake, although it doesn't affect the test:
```
--- main.go.orig	2019-10-30 11:52:42.000000000 +1100
+++ main.go	2019-10-30 11:52:04.000000000 +1100
@@ -42,7 +42,7 @@
 	//fmt.Println("Get new conn from " + c.RemoteAddr().String() + " at listener " + c.LocalAddr().String() + ".")
 	buf := make([]byte, 512)
 	for {
-		_, err := c.Read(buf)
+		n, err := c.Read(buf)
 		if err == io.EOF {
 			return
 		}
@@ -51,7 +51,7 @@
 			fmt.Println(err)
 			continue
 		}
-		_, err = c.Write(buf)
+		_, err = c.Write(buf[:n])
 		if err != nil {
 			fmt.Println("Error writing:")
 			fmt.Println(err)
```

**Comment by anacrolix** [comment]
Running the test continuously I see around 1 MB/s and and 20000 packets/s of network activity, with about a 0.03% failure rate.

**Comment by Jorropo** [comment]
Tested under Ubuntu 18.04 to 19.10 Debian 9.11 and ArmBian 10.
And I personally have about 20% of failure on my laptop, 75% on VPS and a very few (1 to 3%) on my arm server.
That correlate with the number of core. (1 for my vps, 4 for my laptop and 8 for my arm server)

**Comment by Jorropo** [comment]
Also thx for the error, I wasn't knowing (that was a copy paste from somewhere on internet).
But as you said that change nothing.

**Comment by Jorropo** [comment]
Also the same error was triggered on the old pure go implementation (but because its depreacated I obviously not reported there).

**Comment by anacrolix** [comment]
If I run with `GOMAXPROCS=1`, it occurs much more frequently.

**Comment by Jorropo** [comment]
Is it possible to maybe to set a bigger timeout ? (I'm not very experienced with golang so I don't know how context works.)

**Comment by Jorropo** [comment]
After some test closer to the real world its not a real problem, on an 1Gbits/s ethernet I just could not trigger it, I think the 40GBits/s of loopback are just too much, also if there is a small wait (~500µs for me) beetween each Dial that enough to totaly mitigate the problem.

So I'm closing because there is no real need to protect from an 40GBits/s continus flow of connection, I don't think someone will be capable to use a whole QDR infiniband bus of only utp conn.
