### ISSUE TITLE
go build github.com/anacrolix/go-libutp: g++: exec: "g++": executable file not found in $PATH

### ISSUE THREAD

**Issue by greyireland** [anacrolix/go-libutp#21]

**Comment by anacrolix** [comment]
Try setting CXX when you build

**Comment by noslav** [comment]
can you please be a little more explicit here @anacrolix?

**Comment by Jinxuyang** [comment]
If you are running Ubuntu do:

apt-get install build-essential

**Comment by anacrolix** [comment]
Did you resolve this @greyireland ? I suspect this is an issue with your build environment, it's non trivial to walk you through this.

**Comment by greyireland** [comment]
Yes,thks
