### ISSUE TITLE
build issues when cross compiling for android & iOS

### ISSUE THREAD

**Issue by simbadMarino** [anacrolix/go-libutp#23]
Hello, I'm having issues to compile go-libutp on Mac m1 Ventura

**Go Environment:**
GO111MODULE=""
GOARCH="arm64"
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOVERSION="go1.18.3"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/simbadmarino/Documents/btfs-sharedLib/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/89/7_dkrhfd345107kdvp3gk4p40000gn/T/go-build1930779843=/tmp/go-build -gno-record-gcc-switches -fno-common"

Makefile screenshot:

<img width="853" alt="image" src="https://user-images.githubusercontent.com/11146636/209582460-802b408a-0324-482d-8b45-6d192dd7d1ca.png">

What did I do?

make iOS OR make android 

What did I expected?

build is successful 

What happened?

- Following error is shown for iOS:

# github.com/anacrolix/go-libutp
ld: building for macOS, but linking in object file built for iOS Simulator, file '/var/folders/89/7_dkrhfd345107kdvp3gk4p40000gn/T/go-build127800418/b955/_cgo_main.o' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile:19: ios-x86_64] Error 2

-  Following error is shown for Android:

# github.com/anacrolix/go-libutp
ld: warning: ignoring file $WORK/b956/_x005.o, building for macOS-arm64 but attempting to link with file built for unknown-unsupported file format ( 0x7F 0x45 0x4C 0x46 0x01 0x01 0x01 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 )
ld: warning: ignoring file $WORK/b956/_cgo_main.o, building for macOS-arm64 but attempting to link with file built for unknown-unsupported file format ( 0x7F 0x45 0x4C 0x46 0x01 0x01 0x01 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 )
ld: warning: ignoring file $WORK/b956/_x004.o, building for macOS-arm64 but attempting to link with file built for unknown-unsupported file format ( 0x7F 0x45 0x4C 0x46 0x01 0x01 0x01 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 )
ld: warning: ld: warning: ignoring file $WORK/b956/_x001.o, building for macOS-arm64 but attempting to link with file built for unknown-unsupported file format ( 0x7F 0x45 0x4C 0x46 0x01 0x01 0x01 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 )ld: warning: ignoring file $WORK/b956/_x003.o, building for macOS-arm64 but attempting to link with file built for unknown-unsupported file format ( 0x7F 0x45 0x4C 0x46 0x01 0x01 0x01 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 )
ld: warning: ignoring file $WORK/b956/_x007.o, building for macOS-arm64 but attempting to link with file built for unknown-unsupported file format ( 0x7F 0x45 0x4C 0x46 0x01 0x01 0x01 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 )

ld: warning: ignoring file $WORK/b956/_x002.o, building for macOS-arm64 but attempting to link with file built for unknown-unsupported file format ( 0x7F 0x45 0x4C 0x46 0x01 0x01 0x01 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 )
ignoring file $WORK/b956/_x006.o, building for macOS-arm64 but attempting to link with file built for unknown-unsupported file format ( 0x7F 0x45 0x4C 0x46 0x01 0x01 0x01 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 )
Undefined symbols for architecture arm64:
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile:33: android-armv7a] Error 2

Any ideas or support is appreciated. I have tried with old go versions and newer and same result.

**Comment by simbadMarino** [comment]
As a background I'm building [go-btfs ](https://github.com/bittorrent/go-btfs)for mobile which recently integrated go-libutp as dependency .

**Comment by simbadMarino** [comment]
I finally fixed this by moving to go 1.19 and by adding CXX tag on my build for android into my make file.

E.g. : 

before I only had CC , now I have both CC & CXX
CC=$(NDK_BIN)/x86_64-linux-android21-clang \
CXX=$(NDK_BIN)/x86_64-linux-android21-clang++ \


I hope this helps someone out there!

**Comment by anacrolix** [comment]
Fantastic, thank you for following up. Is there anything to continue to the repo to make it easier for others or is it all on your side? Cheers

**Comment by simbadMarino** [comment]
Hello @anacrolix , I know you cannot cover all by your own, this was probably a corner case, specially knowing there are some limitations on android and iOS. Probably a table containing go versions vs already tested OS could help others :)

Thanks for keeping up maintaining this repo :) and the follow up!
