### ISSUE TITLE
is there any specific reason to wrap a clib without updates for 6 years instead of your go lib？

### ISSUE THREAD

**Issue by trim21** [anacrolix/go-libutp#29]

**Comment by anacrolix** [comment]
Are you referring to anacrolix/utp as the go lib?

**Comment by trim21** [comment]
yea

**Comment by anacrolix** [comment]
Yes, the spec for uTP isn't complete or sufficient for an implementation from the spec alone. My Go implementation (and the others by others that came before) wasn't sufficiently correct, and I didn't spend the time to copy the logic from the C++ implementation. It is old and crufty but everyone is using it and it works.

**Comment by trim21** [comment]
thanks for your answer.

and I find another pure go utp impl https://github.com/storj/utp-go

**Comment by anacrolix** [comment]
Awesome, thanks, I wasn't aware of that library. Feel free to drop back in a few months and let me know how it went. If it was reliable I'll consider it as the default non-cgo implementation in anacrolix/torrent.

**Comment by trim21** [comment]
Did a litter testing, it looks fine on single outgoing connection. Not sure how it works with multiple connections

**Comment by anacrolix** [comment]
I'll start looking into adopting it. See the referenced issue.
