### ISSUE TITLE
Panic catched 

### ISSUE THREAD

**Issue by elgatito** [anacrolix/go-libutp#7]
When doing a download user catched a panic.

Log cut: http://paste.ubuntu.com/26064047/
Full log (if needed): http://dropmefiles.com/DEjYE

**Comment by anacrolix** [comment]
Is the first goroutine the panicking one? Can you include that bit?

**Comment by elgatito** [comment]
http://paste.ubuntu.com/26064259/
Sorry, had to re-check user's report. Probably that is something wrong with my code, error is very strange.
