### ISSUE TITLE
go build ucat/main.go fails on linux and windows (undefined: utp.Socket)

### ISSUE THREAD

**Issue by iain17** [anacrolix/go-libutp#9]
When I run:
```GOOS=windows GOARCH=amd64 go build ucat/main.go```
or
```GOOS=linux GOARCH=amd64 go build ucat/main.go```

It seems to fail with the following error:
```
# github.com/anacrolix/go-libutp
../../work/src/github.com/anacrolix/go-libutp/status.go:9:2: undefined: mu
../../work/src/github.com/anacrolix/go-libutp/status.go:10:8: undefined: mu
../../work/src/github.com/anacrolix/go-libutp/status.go:11:20: undefined: libContextToSocket
```
Now I checked out status.go, and it doesn't seem to do much interesting. So after deleting status.go it ends up failing with the following error:
```
GOOS=windows GOARCH=amd64 go build ucat/main.go
# command-line-arguments
ucat/main.go:16:43: undefined: utp.Socket
ucat/main.go:40:21: undefined: utp.Socket
ucat/main.go:42:11: undefined: utp.NewSocket
ucat/main.go:44:11: undefined: utp.NewSocket
ucat/main.go:53:4: not enough arguments to return
ucat/main.go:55:4: not enough arguments to return
```

The "undefined: utp.Socket" error is something I myself got when I started using anacrolix/go-libutp instead of anacrolix/utp. Weirdly enough it does compile on DARWIN.

**Comment by anacrolix** [comment]
You have CGO_ENABLED=0.

**Comment by anacrolix** [comment]
Or are you attempting to cross-compile? I don't think cgo is supported for cross-compilation.

**Comment by iain17** [comment]
Correct, I am trying to compile cross platform. That's why it worked on darwin (mac) and not on the other platforms. Enabling CGO_ENABLED=1 returns a missing windows.h.

Thanks for your reply, I'll stick to the older utp package for now 👍
